version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: storybot_postgres
    environment:
      POSTGRES_DB: storybot
      POSTGRES_USER: storybot
      POSTGRES_PASSWORD: storybot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storybot"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: storybot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://storybot:storybot_password@postgres:5432/storybot
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes:
      - ./:/app
    working_dir: /app
    command: poetry run bot
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: storybot_adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data: